version: "3"
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - mynetwork
    depends_on:
      - gitlab
  gitlab:
    image: gitlab/gitlab-ce
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - gitlab_data:/var/opt/gitlab
    networks:
      - mynetwork
volumes:
  jenkins_data:
  gitlab_data:
networks:
  mynetwork:
    driver: bridge
